version: '3.1'
services:
  app:
    image: 'kry/myapp'
    build:
      context: .
    ports:
      - 8093:8093
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/iban
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=DontAsk12
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=DontAsk12
      - POSTGRES_DB=iban
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
